//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
// Note: requires additional types generated from: options.proto
using Utils;
namespace msg
{

  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DVector2")]
  public partial class DVector2 : msg_base
  {
    public DVector2() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DVector3")]
  public partial class DVector3 : msg_base
  {
    public DVector3() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DCharacter")]
  public partial class DCharacter : msg_base
  {
    public DCharacter() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DHuman")]
  public partial class DHuman : msg_base
  {
    public DHuman() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private DProp _prop = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"prop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DProp prop
    {
      get { return _prop; }
      set { _prop = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _hpCur = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hpCur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpCur
    {
      get { return _hpCur; }
      set { _hpCur = value; }
    }
    private int _mpCur = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mpCur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mpCur
    {
      get { return _mpCur; }
      set { _mpCur = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DProp")]
  public partial class DProp : msg_base
  {
    public DProp() {}
    
    private int _str = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"str", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int str
    {
      get { return _str; }
      set { _str = value; }
    }
    private int _dex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dex
    {
      get { return _dex; }
      set { _dex = value; }
    }
    private int _con = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"con", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int con
    {
      get { return _con; }
      set { _con = value; }
    }
    private int _inte = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"inte", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int inte
    {
      get { return _inte; }
      set { _inte = value; }
    }
    private int _atk = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _hit = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private int _dodge = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dodge
    {
      get { return _dodge; }
      set { _dodge = value; }
    }
    private int _crit = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int crit
    {
      get { return _crit; }
      set { _crit = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _hpMax = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private int _mpMax = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mpMax
    {
      get { return _mpMax; }
      set { _mpMax = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLogin")]
  public partial class CSLogin : msg_base
  {
    public CSLogin() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSLogin;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCLoginResult")]
  public partial class SCLoginResult : msg_base
  {
    public SCLoginResult() {}
    
    private int _resultCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private string _resultReason = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resultReason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultReason
    {
      get { return _resultReason; }
      set { _resultReason = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCLoginResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSAccountReconnect")]
  public partial class CSAccountReconnect : msg_base
  {
    public CSAccountReconnect() {}
    
    private long _sessionKey = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sessionKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSAccountReconnect;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCAccountReconnectResult")]
  public partial class SCAccountReconnectResult : msg_base
  {
    public SCAccountReconnectResult() {}
    
    private int _resultCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCAccountReconnectResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSQueryCharacters")]
  public partial class CSQueryCharacters : msg_base
  {
    public CSQueryCharacters() {}
    
	public override int _msgid(){return MsgDef.msgid_CSQueryCharacters;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCQueryCharactersResult")]
  public partial class SCQueryCharactersResult : msg_base
  {
    public SCQueryCharactersResult() {}
    
    private readonly global::System.Collections.Generic.List<DCharacter> _characters = new global::System.Collections.Generic.List<DCharacter>();
    [global::ProtoBuf.ProtoMember(1, Name=@"characters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DCharacter> characters
    {
      get { return _characters; }
    }
  
	public override int _msgid(){return MsgDef.msgid_SCQueryCharactersResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSCharacterCreate")]
  public partial class CSCharacterCreate : msg_base
  {
    public CSCharacterCreate() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _profession;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSCharacterCreate;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCCharacterCreateResult")]
  public partial class SCCharacterCreateResult : msg_base
  {
    public SCCharacterCreateResult() {}
    
    private int _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private string _resultReason = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resultReason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultReason
    {
      get { return _resultReason; }
      set { _resultReason = value; }
    }
    private long _humanId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"humanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long humanId
    {
      get { return _humanId; }
      set { _humanId = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCCharacterCreateResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSCharacterDelete")]
  public partial class CSCharacterDelete : msg_base
  {
    public CSCharacterDelete() {}
    
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSCharacterDelete;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCCharacterDeleteResult")]
  public partial class SCCharacterDeleteResult : msg_base
  {
    public SCCharacterDeleteResult() {}
    
    private int _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCCharacterDeleteResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSCharacterLogin")]
  public partial class CSCharacterLogin : msg_base
  {
    public CSCharacterLogin() {}
    
    private long _humanId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"humanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long humanId
    {
      get { return _humanId; }
      set { _humanId = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSCharacterLogin;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCCharacterLoginResult")]
  public partial class SCCharacterLoginResult : msg_base
  {
    public SCCharacterLoginResult() {}
    
    private int _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCCharacterLoginResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCInitData")]
  public partial class SCInitData : msg_base
  {
    public SCInitData() {}
    
    private DHuman _human = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"human", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DHuman human
    {
      get { return _human; }
      set { _human = value; }
    }
    private DInitDataStage _stage = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DInitDataStage stage
    {
      get { return _stage; }
      set { _stage = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCInitData;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DInitDataStage")]
  public partial class DInitDataStage : msg_base
  {
    public DInitDataStage() {}
    
    private DVector2 _posNow;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"posNow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DVector2 posNow
    {
      get { return _posNow; }
      set { _posNow = value; }
    }
    private long _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _sn;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sn
    {
      get { return _sn; }
      set { _sn = value; }
    }
    private int _instanceSn = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"instanceSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int instanceSn
    {
      get { return _instanceSn; }
      set { _instanceSn = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCHumanKick")]
  public partial class SCHumanKick : msg_base
  {
    public SCHumanKick() {}
    
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCHumanKick;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSStageEnter")]
  public partial class CSStageEnter : msg_base
  {
    public CSStageEnter() {}
    
	public override int _msgid(){return MsgDef.msgid_CSStageEnter;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageEnterResult")]
  public partial class SCStageEnterResult : msg_base
  {
    public SCStageEnterResult() {}
    
    private readonly global::System.Collections.Generic.List<DStageObject> _obj = new global::System.Collections.Generic.List<DStageObject>();
    [global::ProtoBuf.ProtoMember(1, Name=@"obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DStageObject> obj
    {
      get { return _obj; }
    }
  
	public override int _msgid(){return MsgDef.msgid_SCStageEnterResult;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSStageSwitch")]
  public partial class CSStageSwitch : msg_base
  {
    public CSStageSwitch() {}
    
    private string _areaSwitchKey = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"areaSwitchKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string areaSwitchKey
    {
      get { return _areaSwitchKey; }
      set { _areaSwitchKey = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSStageSwitch;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageSwitch")]
  public partial class SCStageSwitch : msg_base
  {
    public SCStageSwitch() {}
    
    private long _stageId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stageId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long stageId
    {
      get { return _stageId; }
      set { _stageId = value; }
    }
    private int _stageSn = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stageSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stageSn
    {
      get { return _stageSn; }
      set { _stageSn = value; }
    }
    private DVector2 _pos = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCStageSwitch;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSStageMove")]
  public partial class CSStageMove : msg_base
  {
    public CSStageMove() {}
    
    private DVector2 _posBegin = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posBegin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 posBegin
    {
      get { return _posBegin; }
      set { _posBegin = value; }
    }
    private readonly global::System.Collections.Generic.List<DVector2> _posEnd = new global::System.Collections.Generic.List<DVector2>();
    [global::ProtoBuf.ProtoMember(2, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DVector2> posEnd
    {
      get { return _posEnd; }
    }
  
	public override int _msgid(){return MsgDef.msgid_CSStageMove;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageMove")]
  public partial class SCStageMove : msg_base
  {
    public SCStageMove() {}
    
    private long _objId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private DVector2 _posBegin = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posBegin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 posBegin
    {
      get { return _posBegin; }
      set { _posBegin = value; }
    }
    private readonly global::System.Collections.Generic.List<DVector2> _posEnd = new global::System.Collections.Generic.List<DVector2>();
    [global::ProtoBuf.ProtoMember(3, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DVector2> posEnd
    {
      get { return _posEnd; }
    }
  
	public override int _msgid(){return MsgDef.msgid_SCStageMove;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageSetPos")]
  public partial class SCStageSetPos : msg_base
  {
    public SCStageSetPos() {}
    
    private long _humanId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"humanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long humanId
    {
      get { return _humanId; }
      set { _humanId = value; }
    }
    private readonly global::System.Collections.Generic.List<DVector2> _pos = new global::System.Collections.Generic.List<DVector2>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DVector2> pos
    {
      get { return _pos; }
    }
  
	public override int _msgid(){return MsgDef.msgid_SCStageSetPos;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSStageMoveStop")]
  public partial class CSStageMoveStop : msg_base
  {
    public CSStageMoveStop() {}
    
    private DVector2 _posEnd = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 posEnd
    {
      get { return _posEnd; }
      set { _posEnd = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSStageMoveStop;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageMoveStop")]
  public partial class SCStageMoveStop : msg_base
  {
    public SCStageMoveStop() {}
    
    private long _objId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private DVector2 _posEnd = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 posEnd
    {
      get { return _posEnd; }
      set { _posEnd = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCStageMoveStop;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DStageHuman")]
  public partial class DStageHuman : msg_base
  {
    public DStageHuman() {}
    
    private readonly global::System.Collections.Generic.List<DVector2> _posEnd = new global::System.Collections.Generic.List<DVector2>();
    [global::ProtoBuf.ProtoMember(1, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DVector2> posEnd
    {
      get { return _posEnd; }
    }
  
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _profession = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"profession", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profession
    {
      get { return _profession; }
      set { _profession = value; }
    }
    private int _hpCur = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hpCur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpCur
    {
      get { return _hpCur; }
      set { _hpCur = value; }
    }
    private int _hpMax = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private int _mpCur = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mpCur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mpCur
    {
      get { return _mpCur; }
      set { _mpCur = value; }
    }
    private int _mpMax = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mpMax
    {
      get { return _mpMax; }
      set { _mpMax = value; }
    }
    private bool _evil = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"evil", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool evil
    {
      get { return _evil; }
      set { _evil = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private long _teamId = default(long);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private long _unionId = default(long);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"unionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long unionId
    {
      get { return _unionId; }
      set { _unionId = value; }
    }
    private long _countryId = default(long);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"countryId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long countryId
    {
      get { return _countryId; }
      set { _countryId = value; }
    }
    private int _equipWeaponSn = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"equipWeaponSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipWeaponSn
    {
      get { return _equipWeaponSn; }
      set { _equipWeaponSn = value; }
    }
    private int _equipClothesSn = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"equipClothesSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipClothesSn
    {
      get { return _equipClothesSn; }
      set { _equipClothesSn = value; }
    }
    private int _equipWeaponStrthLevel = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"equipWeaponStrthLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipWeaponStrthLevel
    {
      get { return _equipWeaponStrthLevel; }
      set { _equipWeaponStrthLevel = value; }
    }
    private string _pvpMode = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"pvpMode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pvpMode
    {
      get { return _pvpMode; }
      set { _pvpMode = value; }
    }
    private bool _inFighting = default(bool);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"inFighting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool inFighting
    {
      get { return _inFighting; }
      set { _inFighting = value; }
    }
    private int _titleSn = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"titleSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int titleSn
    {
      get { return _titleSn; }
      set { _titleSn = value; }
    }
    private int _combat = default(int);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"combat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int combat
    {
      get { return _combat; }
      set { _combat = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DStageMonster")]
  public partial class DStageMonster : msg_base
  {
    public DStageMonster() {}
    
    private readonly global::System.Collections.Generic.List<DVector2> _posEnd = new global::System.Collections.Generic.List<DVector2>();
    [global::ProtoBuf.ProtoMember(1, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DVector2> posEnd
    {
      get { return _posEnd; }
    }
  
    private int _monsterSn = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"monsterSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monsterSn
    {
      get { return _monsterSn; }
      set { _monsterSn = value; }
    }
    private int _hpCur = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hpCur", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpCur
    {
      get { return _hpCur; }
      set { _hpCur = value; }
    }
    private int _hpMax = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hpMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hpMax
    {
      get { return _hpMax; }
      set { _hpMax = value; }
    }
    private int _collisionRadius = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"collisionRadius", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int collisionRadius
    {
      get { return _collisionRadius; }
      set { _collisionRadius = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private bool _active = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"active", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool active
    {
      get { return _active; }
      set { _active = value; }
    }
    private int _face = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"face", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int face
    {
      get { return _face; }
      set { _face = value; }
    }
    private string _pvpMode = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pvpMode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pvpMode
    {
      get { return _pvpMode; }
      set { _pvpMode = value; }
    }
    private int _pvpDiWoId = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"pvpDiWoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pvpDiWoId
    {
      get { return _pvpDiWoId; }
      set { _pvpDiWoId = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DStageDrop")]
  public partial class DStageDrop : msg_base
  {
    public DStageDrop() {}
    
    private string _type = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _itemSn = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemSn
    {
      get { return _itemSn; }
      set { _itemSn = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private long _humanId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"humanId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long humanId
    {
      get { return _humanId; }
      set { _humanId = value; }
    }
    private int _protectTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"protectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int protectTime
    {
      get { return _protectTime; }
      set { _protectTime = value; }
    }
    private int _bind = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bind
    {
      get { return _bind; }
      set { _bind = value; }
    }
    private long _monsterId = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DStagePick")]
  public partial class DStagePick : msg_base
  {
    public DStagePick() {}
    
    private int _pickSn = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pickSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pickSn
    {
      get { return _pickSn; }
      set { _pickSn = value; }
    }
    private DVector2 _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private bool _visible = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"visible", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool visible
    {
      get { return _visible; }
      set { _visible = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DStageNPC")]
  public partial class DStageNPC : msg_base
  {
    public DStageNPC() {}
    
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DStageObject")]
  public partial class DStageObject : msg_base
  {
    public DStageObject() {}
    
    private DVector2 _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private long _objId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private string _modelSn = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"modelSn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modelSn
    {
      get { return _modelSn; }
      set { _modelSn = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private EWorldObjectType _type = EWorldObjectType.HUMAN;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(EWorldObjectType.HUMAN)]
    public EWorldObjectType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private DStageHuman _human = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"human", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DStageHuman human
    {
      get { return _human; }
      set { _human = value; }
    }
    private DStageMonster _monster = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"monster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DStageMonster monster
    {
      get { return _monster; }
      set { _monster = value; }
    }
    private DStageDrop _drop = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"drop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DStageDrop drop
    {
      get { return _drop; }
      set { _drop = value; }
    }
    private DStagePick _pick = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DStagePick pick
    {
      get { return _pick; }
      set { _pick = value; }
    }
    private DStageNPC _npc = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"npc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DStageNPC npc
    {
      get { return _npc; }
      set { _npc = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageObjectAppear")]
  public partial class SCStageObjectAppear : msg_base
  {
    public SCStageObjectAppear() {}
    
    private DStageObject _objAppear = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objAppear", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DStageObject objAppear
    {
      get { return _objAppear; }
      set { _objAppear = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCStageObjectAppear;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageObjectDisappear")]
  public partial class SCStageObjectDisappear : msg_base
  {
    public SCStageObjectDisappear() {}
    
    private long _objId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _killerName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"killerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string killerName
    {
      get { return _killerName; }
      set { _killerName = value; }
    }
    private long _killerId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"killerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long killerId
    {
      get { return _killerId; }
      set { _killerId = value; }
    }
    private int _skillSn = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillSn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillSn
    {
      get { return _skillSn; }
      set { _skillSn = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCStageObjectDisappear;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStageMoveTeleport")]
  public partial class SCStageMoveTeleport : msg_base
  {
    public SCStageMoveTeleport() {}
    
    private long _objId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"objId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long objId
    {
      get { return _objId; }
      set { _objId = value; }
    }
    private DVector2 _posEnd = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posEnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 posEnd
    {
      get { return _posEnd; }
      set { _posEnd = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCStageMoveTeleport;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSStageMove2")]
  public partial class CSStageMove2 : msg_base
  {
    public CSStageMove2() {}
    
    private DVector2 _posBegin = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posBegin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 posBegin
    {
      get { return _posBegin; }
      set { _posBegin = value; }
    }
    private DVector2 _direction = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSStageMove2;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCStagePullTo")]
  public partial class SCStagePullTo : msg_base
  {
    public SCStagePullTo() {}
    
    private DVector2 _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DVector2 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCStagePullTo;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSTest")]
  public partial class CSTest : msg_base
  {
    public CSTest() {}
    
    private int _cscode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cscode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cscode
    {
      get { return _cscode; }
      set { _cscode = value; }
    }
    private string _csstring = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"csstring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string csstring
    {
      get { return _csstring; }
      set { _csstring = value; }
    }
	public override int _msgid(){return MsgDef.msgid_CSTest;}
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCTest")]
  public partial class SCTest : msg_base
  {
    public SCTest() {}
    
    private int _sccode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sccode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sccode
    {
      get { return _sccode; }
      set { _sccode = value; }
    }
    private string _scstring = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"scstring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scstring
    {
      get { return _scstring; }
      set { _scstring = value; }
    }
	public override int _msgid(){return MsgDef.msgid_SCTest;}
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EWorldObjectType")]
    public enum EWorldObjectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HUMAN", Value=0)]
      HUMAN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONSTER", Value=1)]
      MONSTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DROP", Value=2)]
      DROP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DOT", Value=3)]
      DOT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NPC", Value=4)]
      NPC = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PICK", Value=5)]
      PICK = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIGGER", Value=6)]
      TRIGGER = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=7)]
      COMMON = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EstageCommonType")]
    public enum EstageCommonType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"common", Value=1)]
      common = 1
    }
  
}